### ISSUE TITLE
Creating login/Signup forms and About pages

### ISSUE THREAD

**Issue by Magpiny** [BuildForSDGCohort2/team-44K-frontend#3]
creating login, signup and About  components and testing them thoroughly 

- [x] creating signup  components

**Comment by jakazzy** [comment]
Seen I just cloned the repo

**Comment by jakazzy** [comment]
I clicked on the Login and sign up links but I but routing did not work. Setup routing already to the components?

**Comment by Magpiny** [comment]
I just did the routings today so I'll update as soon as I can.
Thanks for understanding

**Comment by jakazzy** [comment]
Sure great!

**Comment by Magpiny** [comment]
Done
